# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Comparator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Comparator(object):
    def setupUi(self, Comparator):
        Comparator.setObjectName("Comparator")
        Comparator.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Comparator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.conclusion = QtWidgets.QLabel(self.gridLayoutWidget)
        self.conclusion.setText("")
        self.conclusion.setObjectName("conclusion")
        self.gridLayout_4.addWidget(self.conclusion, 0, 1, 1, 1)
        self.myPkm = QtWidgets.QLabel(self.gridLayoutWidget)
        self.myPkm.setText("")
        self.myPkm.setObjectName("myPkm")
        self.gridLayout_4.addWidget(self.myPkm, 0, 0, 1, 1)
        self.rivalPkm = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rivalPkm.setText("")
        self.rivalPkm.setObjectName("rivalPkm")
        self.gridLayout_4.addWidget(self.rivalPkm, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 6, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.getMyPkm = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.getMyPkm.setObjectName("getMyPkm")
        self.gridLayout_2.addWidget(self.getMyPkm, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.getRivalPkm = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.getRivalPkm.setObjectName("getRivalPkm")
        self.gridLayout_2.addWidget(self.getRivalPkm, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.myPkmTypes = QtWidgets.QLabel(self.gridLayoutWidget)
        self.myPkmTypes.setObjectName("myPkmTypes")
        self.gridLayout_3.addWidget(self.myPkmTypes, 2, 0, 1, 1)
        self.rivalPkmtypes = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rivalPkmtypes.setObjectName("rivalPkmtypes")
        self.gridLayout_3.addWidget(self.rivalPkmtypes, 2, 1, 1, 1)
        self.rivalPkmName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rivalPkmName.setObjectName("rivalPkmName")
        self.gridLayout_3.addWidget(self.rivalPkmName, 1, 1, 1, 1)
        self.myPkmName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.myPkmName.setObjectName("myPkmName")
        self.gridLayout_3.addWidget(self.myPkmName, 1, 0, 1, 1)
        self.myPkmSprite = QtWidgets.QLabel(self.gridLayoutWidget)
        self.myPkmSprite.setObjectName("myPkmSprite")
        self.gridLayout_3.addWidget(self.myPkmSprite, 0, 0, 1, 1)
        self.rivalPkmSprite = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rivalPkmSprite.setObjectName("rivalPkmSprite")
        self.gridLayout_3.addWidget(self.rivalPkmSprite, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 5, 1, 1, 1)
        self.getPkms = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.getPkms.setObjectName("getPkms")
        self.gridLayout.addWidget(self.getPkms, 3, 2, 1, 1)
        Comparator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Comparator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 32))
        self.menubar.setObjectName("menubar")
        Comparator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Comparator)
        self.statusbar.setObjectName("statusbar")
        Comparator.setStatusBar(self.statusbar)

        self.retranslateUi(Comparator)
        QtCore.QMetaObject.connectSlotsByName(Comparator)

    def retranslateUi(self, Comparator):
        _translate = QtCore.QCoreApplication.translate
        Comparator.setWindowTitle(_translate("Comparator", "MainWindow"))
        self.label.setText(_translate("Comparator", "Mi Pokemon es:"))
        self.label_2.setText(_translate("Comparator", "El Pokemon rival es:"))
        self.myPkmTypes.setText(_translate("Comparator", "Types"))
        self.rivalPkmtypes.setText(_translate("Comparator", "Types"))
        self.rivalPkmName.setText(_translate("Comparator", "Name"))
        self.myPkmName.setText(_translate("Comparator", "Name"))
        self.myPkmSprite.setText(_translate("Comparator", "Img"))
        self.rivalPkmSprite.setText(_translate("Comparator", "Img"))
        self.getPkms.setText(_translate("Comparator", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Comparator = QtWidgets.QMainWindow()
    ui = Ui_Comparator()
    ui.setupUi(Comparator)
    Comparator.show()
    sys.exit(app.exec_())
